services:

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    # Command to obtain certificates will be run manually first
    command: "echo 'Certbot container is ready to use.'"
  web:
    container_name: madebyphil-home
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped
